const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const path = require("node:path");
const vm = require("node:vm");

/** 名前抽選・固定敵・期限・補充・報酬の一度だけの適用と犯罪期限を実モジュールで検証する。 @returns {Promise<void>} */
async function main() {
  const fixedMath = Object.create(Math); fixedMath.random = () => 0.5;
  const context = vm.createContext({ structuredClone, Math: fixedMath });
  const modules = new Map();
  const state = { year: 1000, season: 0, day: 1, funds: 0, honorFactions: [], troops: {} };
  const favors = {};
  const factions = ["north", "archipelago", "citadel", "pirates"].map(id => ({ id, nobles: [{ id: id + "1" }, { id: id + "2" }] }));
  const stubs = {
    "state.js": { state }, "map.js": { mapData: [] },
    "questUtils.js": { absDay: s => s.year * 120 + s.season * 30 + s.day },
    "faction.js": { adjustNobleFavor: (id, n) => { favors[id] = (favors[id] || 0) + n; } },
    "lore.js": { FACTIONS: factions }, "dom.js": { pushLog() {} },
  };
  /** @param {string} name モジュール。 @returns {Promise<vm.Module>} 検証対象。 */
  async function load(name) {
    name = name.replace(/^\.\//, "");
    if (modules.has(name)) return modules.get(name);
    const exports = stubs[name];
    const mod = exports ? new vm.SyntheticModule(Object.keys(exports), function () {
      for (const [key, value] of Object.entries(exports)) this.setExport(key, value);
    }, { context }) : new vm.SourceTextModule(await fs.readFile(path.join(__dirname, "..", name), "utf8"), { context });
    modules.set(name, mod); await mod.link(load); return mod;
  }
  const core = await load("bounty.js"); await core.evaluate();
  const policyModule = await load("wantedPolicy.js"); await policyModule.evaluate();
  const policy = policyModule.namespace;
  const identityModule = await load("identityPolicy.js"); await identityModule.evaluate();
  const modesModule = await load("constants.js"); await modesModule.evaluate();
  const mode = modesModule.namespace.MODE_LABEL;
  for (const modeLabel of [mode.NORMAL, mode.IN_TOWN, mode.IN_VILLAGE, mode.AUDIENCE]) {
    assert.equal(identityModule.namespace.canManageIdentity({modeLabel}),true,"所属変更は場所に依存しない");
    assert.equal(identityModule.namespace.canManageIdentity({modeLabel,eventQueue:[{}]}),false);
    assert.equal(identityModule.namespace.canManageIdentity({modeLabel,pendingEncounter:{active:true}}),false);
  }
  assert.equal(identityModule.namespace.canManageIdentity({modeLabel:mode.BATTLE}),false);
  const judicialModule = await load("judicialDeal.js"); await judicialModule.evaluate();
  const judicial = judicialModule.namespace;
  const informant = {year:1000,season:0,day:1,honorFactions:[],supplies:{illegal_drug:40},nobleFavor:{pirate_blackbeard:-90},wanted:{version:2,byFaction:{north:{amount:4000,lastCrimeAbs:120001},pirates:{amount:500,lastCrimeAbs:120001}}}};
  const tribunal={id:"court",factionId:"north"};
  assert.ok(judicial.quoteJudicialDeal(informant,{pirateHaven:true},"illegal_drug").error);
  informant.honorFactions=["citadel"];
  assert.equal(judicial.applyJudicialDeal(informant,tribunal,"illegal_drug",4000),false);
  informant.honorFactions=[];
  assert.equal(judicial.applyJudicialDeal(informant,tribunal,"illegal_drug",3000),false);
  assert.equal(judicial.applyJudicialDeal(informant,tribunal,"illegal_drug",4000),true);
  assert.equal(informant.wanted.byFaction.north.amount,1000);
  assert.equal(informant.wanted.byFaction.pirates.amount,1500);
  assert.equal(informant.supplies.illegal_drug,30);
  assert.equal(informant.nobleFavor.pirate_blackbeard,-100);
  assert.equal(informant.wanted.history[0].kind,"judicial_deal");
  assert.equal(judicial.applyJudicialDeal(informant,tribunal,"illegal_drug",1000),false);
  informant.season=1;
  assert.equal(judicial.applyJudicialDeal(informant,tribunal,"illegal_drug",1000),true);
  assert.equal(informant.wanted.byFaction.north.lastCrimeAbs,null);
  assert.equal(informant.wanted.byFaction.pirates.lastCrimeAbs,120031);
  assert.equal(informant.wanted.judicialUntil,120061);
  const forgedModule = await load("forgery.js"); await forgedModule.evaluate();
  const forged = forgedModule.namespace;
  const client = {year:1000,season:0,day:1,funds:10000,wanted:{version:2,byFaction:{north:{amount:1001,lastCrimeAbs:120001},pirates:{amount:500,lastCrimeAbs:120001}}}};
  const haven = {id:"haven",pirateHaven:true};
  assert.ok(forged.quoteForgery(client,{},"north").error);
  assert.ok(forged.quoteForgery(client,haven,"pirates").error);
  assert.equal(forged.quoteForgery(client,haven,"north").cost,501);
  assert.equal(forged.applyForgery(client,haven,"north",1001,500),false);
  assert.equal(forged.applyForgery(client,haven,"north",1001,501),true);
  assert.equal(client.funds,9499);
  assert.equal(client.wanted.byFaction.north.amount,500);
  assert.equal(client.wanted.byFaction.pirates.amount,500);
  assert.equal(client.wanted.byFaction.north.lastCrimeAbs,120001);
  assert.ok(forged.quoteForgery(client,haven,"north").error);
  const wantedModule=await load("playerWanted.js"); await wantedModule.evaluate();
  client.wanted=wantedModule.namespace.normalizeWanted(JSON.parse(JSON.stringify(client.wanted)));
  assert.equal(client.wanted.forgeryUntil,120031);
  client.season=1;
  assert.equal(forged.quoteForgery(client,haven,"north").cost,250);
  client.nobleFavor={pirate_blackbeard:30};
  assert.equal(forged.quoteForgery(client,haven,"north").cost,200);
  client.funds=199;
  assert.equal(forged.applyForgery(client,haven,"north",500,200),false);
  client.day=601;
  assert.ok(forged.quoteForgery(client,haven,"north").error);
  const amnestyModule = await load("amnesty.js"); await amnestyModule.evaluate();
  const amnesty = amnestyModule.namespace;
  const petitioner = { year: 1000, season: 0, day: 1, supplies: { food: 100 }, quests: { active: [], nextId: 1 }, wanted: { byFaction: { north: { amount: 1500, lastCrimeAbs: 120001 }, pirates: { amount: 500, lastCrimeAbs: 120001 } }, history: [{ kind: "theft_market" }] } };
  const office = { id: "port", name: "港", factionId: "north" };
  const pardon = amnesty.acceptAmnesty(petitioner, office);
  assert.equal(pardon.deadlineAbs, 120061);
  assert.equal(amnesty.acceptAmnesty(petitioner, { ...office, factionId: "pirates" }), null);
  assert.equal(amnesty.completeAmnesty(petitioner, pardon, { ...office, id: "other" }), 0);
  assert.equal(amnesty.completeAmnesty(petitioner, pardon, { ...office, factionId: "citadel" }), 1000);
  assert.equal(petitioner.wanted.byFaction.north.amount, 500);
  assert.equal(petitioner.wanted.byFaction.pirates.amount, 500);
  assert.equal(petitioner.supplies.food, 50);
  assert.equal(petitioner.wanted.history.length, 1);
  assert.equal(amnesty.completeAmnesty(petitioner, pardon, office), 0);
  assert.equal(amnesty.acceptAmnesty(petitioner, office), null);
  petitioner.season++;
  const nextPardon = amnesty.acceptAmnesty(petitioner, office);
  petitioner.season = 3;
  petitioner.day = 2;
  assert.equal(amnesty.canCompleteAmnesty(petitioner, nextPardon, office), false);
  petitioner.season = 1;
  petitioner.day = 1;
  assert.equal(amnesty.completeAmnesty(petitioner, nextPardon, office), 500);
  assert.equal(petitioner.wanted.byFaction.north.lastCrimeAbs, null);
  const theftModule = await load("settlementCrime.js"); await theftModule.evaluate();
  const theft = theftModule.namespace;
  assert.equal(theft.rollCrimeReward({kind:"village"},"theft_market",()=>0).funds,200);
  assert.equal(theft.rollCrimeReward({kind:"town"},"theft_market",()=>0.999999).funds,900);
  assert.equal(theft.crimeScale({kind:"village"}),0.5);
  assert.equal(theft.crimeScale({kind:"town"}),1.5);
  const thief = { year: 1000, season: 0, day: 1, modeLabel: "街の中", funds: 0, supplies: {}, honorFactions: [] };
  const victim = { id: "victim", factionId: "north" };
  assert.equal(theft.commitTheft(thief, victim, "theft_granary", 34), false);
  assert.equal(thief.wanted, undefined);
  assert.equal(theft.commitTheft(thief, victim, "theft_market", 35), true);
  assert.equal(thief.funds, 500);
  assert.equal(thief.supplies.salt, 2);
  assert.equal(thief.wanted.byFaction.north.amount, 500);
  assert.equal(theft.commitTheft(thief, victim, "theft_granary", 35), false);
  const wantedForTheft = await load("playerWanted.js"); await wantedForTheft.evaluate();
  thief.wanted = wantedForTheft.namespace.normalizeWanted(thief.wanted);
  assert.equal(theft.commitTheft(thief, { ...victim, factionId: "pirates" }, "theft_market", 35), false);
  thief.season++;
  thief.honorFactions = ["citadel"];
  assert.equal(theft.commitTheft(thief, victim, "theft_market", 35), false);
  thief.honorFactions = [];
  assert.equal(theft.commitTheft(thief, { ...victim, factionId: "pirates" }, "theft_granary", 100), true);
  assert.equal(thief.wanted.byFaction.pirates.amount, 1000);
  assert.equal(thief.supplies.food, 30);
  thief.season++;
  assert.equal(theft.commitTheft(thief, victim, "theft_armory", 100), false);
  thief.troops = { infantry: { 1: 10 } };
  assert.equal(theft.commitTheft(thief, victim, "theft_armory", 100), true);
  assert.equal(thief.supplies.arms, undefined);
  assert.equal(theft.commitTheft(thief, victim, "theft_market", 100), false);
  const armory = { theftKind: "theft_armory", theftReward: { arms: 8, iron: 10 } };
  assert.equal(theft.finishTheftBattle(thief, structuredClone(armory), false).length, 0);
  assert.equal(theft.finishTheftBattle(thief, armory, true).length, 2);
  assert.equal(thief.supplies.arms, 8);
  assert.equal(theft.finishTheftBattle(thief, armory, true).length, 0);
  const raidDay = thief.year * 120 + thief.season * 30 + thief.day;
  const outside = structuredClone(thief);
  outside.modeLabel=mode.NORMAL;
  outside.wanted.byFaction.north={amount:6000,lastCrimeAbs:raidDay};
  assert.ok(policy.wantedEntryReason(outside,victim,raidDay));
  assert.equal(theft.theftReason(outside,victim,"settlement_raid",100),"","入場拒否でも入口から襲撃可能");
  assert.ok(theft.theftReason(outside,victim,"theft_market",100),"窃盗は入場が必要");
  assert.equal(theft.commitTheft(thief, victim, "settlement_raid", 100), true, "窃盗とは別枠で襲撃できる");
  assert.equal(thief.wanted.settlementActions.victim.theftSeason, thief.year * 4 + thief.season);
  assert.equal(thief.wanted.settlementActions.victim.bannedUntil, raidDay + 30);
  thief.wanted = wantedForTheft.namespace.normalizeWanted(thief.wanted);
  thief.wanted.byFaction.north.amount = 0;
  assert.ok(policy.wantedEntryReason(thief, { ...victim, factionId: "citadel" }, raidDay + 29));
  assert.equal(policy.wantedEntryReason(thief, { ...victim, factionId: "citadel" }, raidDay + 30), "");
  assert.equal(theft.commitTheft(thief, victim, "settlement_raid", 100), false);
  const raid = { theftKind: "settlement_raid", theftReward: { food: 50, wood: 10 }, theftFunds: 5000 };
  const raidFunds = thief.funds;
  assert.equal(theft.finishTheftBattle(thief, structuredClone(raid), false).length, 0);
  assert.equal(theft.finishTheftBattle(thief, raid, true).length, 3);
  assert.equal(thief.funds, raidFunds + 5000);
  assert.equal(theft.finishTheftBattle(thief, raid, true).length, 0);
  const pursuitModule = await load("pursuit.js"); await pursuitModule.evaluate();
  const pursuitRules = pursuitModule.namespace;
  const hunterState = { fame: 0, wanted: { byFaction: { north: { amount: 2000, lastCrimeAbs: 1 }, pirates: { amount: 1000, lastCrimeAbs: 1 } } } };
  assert.equal(pursuitRules.hunterTier(hunterState, 600).bounty, 3000);
  assert.equal(pursuitRules.hunterTier(hunterState, 601), null);
  hunterState.wanted.byFaction.north.amount = Number.MAX_SAFE_INTEGER;
  assert.equal(pursuitRules.hunterTier(hunterState, 2).max, 160);
  hunterState.fame = 999999;
  assert.equal(pursuitRules.hunterTier(hunterState, 2).max, 160);
  assert.equal(pursuitRules.hunterTier({ wanted: {} }, 2), null);
  const chased = { wanted: {} }, chase = { pursuitKind: "regular" };
  assert.equal(pursuitRules.finishPursuit(chased, {}, 10), false);
  assert.equal(pursuitRules.finishPursuit(chased, chase, 10), true);
  assert.equal(pursuitRules.canRollPursuit(chased, 12), false);
  assert.equal(pursuitRules.canRollPursuit(chased, 13), true);
  assert.equal(pursuitRules.finishPursuit(chased, chase, 12), false);
  assert.equal(chased.wanted.pursuitUntil, 13);
  chased.pendingEncounter = { active: true };
  assert.equal(pursuitRules.canRollPursuit(chased, 13), false);
  const entryState = { wanted: { byFaction: { north: { amount: 6000, lastCrimeAbs: 1 }, pirates: { amount: 6000, lastCrimeAbs: 1 } } } };
  assert.ok(policy.wantedEntryReason(entryState, { factionId: "north" }, 600));
  assert.equal(policy.wantedEntryReason(entryState, { factionId: "north" }, 601), "");
  assert.equal(policy.wantedEntryReason(entryState, { factionId: "citadel" }, 2), "");
  assert.ok(policy.wantedEntryReason(entryState, { factionId: "pirates", pirateHaven: true }, 2));
  assert.equal(policy.wantedFacilityReason(entryState, { factionId: "pirates", pirateHaven: true }, "quest", 2), "");
  entryState.wanted.byFaction.north.amount = 5999;
  assert.equal(policy.wantedEntryReason(entryState, { factionId: "north" }, 2), "");
  const detentionModule = await load("detention.js"); await detentionModule.evaluate();
  const detention = detentionModule.namespace;
  const prisoner = { year: 1000, season: 3, day: 30, funds: 100, wanted: { byFaction: { north: { amount: 3000, lastCrimeAbs: 120001 }, pirates: { amount: 1000, lastCrimeAbs: 120001 } }, detention: { factionId: "north", remaining: 60 } } };
  const jailQuote = detention.quoteDetention(prisoner, "north");
  assert.equal(jailQuote.days, 60);
  assert.equal(jailQuote.upkeepCount, 2);
  assert.equal(jailQuote.year, 1001);
  assert.equal(jailQuote.season, 1);
  assert.equal(jailQuote.day, 30);
  let worldDay = 0;
  const jailServices = { advance: () => { prisoner.funds--; worldDay++; }, snapshotWorld: () => ({ worldDay }), restoreWorld: world => { worldDay = world.worldDay; }, save: () => false };
  assert.equal(detention.finishDetention(prisoner, jailServices), false);
  assert.equal(prisoner.funds, 100);
  assert.equal(prisoner.wanted.detention.remaining, 60);
  assert.equal(worldDay, 0);
  jailServices.save = () => true;
  assert.equal(detention.finishDetention(prisoner, jailServices), true);
  assert.equal(prisoner.funds, 40);
  assert.equal(prisoner.wanted.byFaction.north.amount, 0);
  assert.equal(prisoner.wanted.byFaction.pirates.amount, 1000);
  assert.equal(prisoner.wanted.detention, null);
  assert.equal(detention.finishDetention(prisoner, jailServices), true);
  assert.equal(worldDay, 60);
  const foodModule = await load("wantedFood.js"); await foodModule.evaluate();
  const food = foodModule.namespace;
  const buyer = { year: 1000, season: 0, funds: 1000, supplies: {}, wanted: { emergencyFood: {} } };
  const port = { id: "port" };
  assert.equal(food.quoteEmergencyFood(buyer, port, 5, 100).unitPrice, 8);
  assert.equal(food.buyEmergencyFood(buyer, port, 5, 100, 31, 8), false);
  assert.equal(food.buyEmergencyFood(buyer, port, 5, 5, 6, 8), false);
  assert.equal(food.buyEmergencyFood(buyer, port, 6, 100, 5, 8), false);
  assert.equal(food.buyEmergencyFood(buyer, port, 5, 100, 20, 8), true);
  assert.equal(buyer.funds, 840);
  assert.equal(food.quoteEmergencyFood(buyer, port, 5, 100).remaining, 10);
  const normalizedModule = await load("playerWanted.js"); await normalizedModule.evaluate();
  buyer.wanted = normalizedModule.namespace.normalizeWanted(buyer.wanted);
  assert.equal(food.quoteEmergencyFood(buyer, port, 5, 100).remaining, 10);
  buyer.season = 1;
  assert.equal(food.quoteEmergencyFood(buyer, port, 5, 100).remaining, 30);
  buyer.funds = 7;
  assert.equal(food.buyEmergencyFood(buyer, port, 5, 100, 1, 8), false);
  const trader = { wanted: { byFaction: { north: { amount: 3000, lastCrimeAbs: 1 } } } };
  for (const service of ["trade", "shipBuy"]) assert.ok(policy.wantedFacilityReason(trader, { factionId: "north" }, service, 2));
  assert.equal(policy.wantedFacilityReason(trader, { factionId: "north" }, "shipSell", 2), "");
  trader.wanted.byFaction.north.amount = 2999;
  assert.equal(policy.wantedFacilityReason(trader, { factionId: "north" }, "trade", 2), "");
  const wantedVisitor = { wanted: { byFaction: { north: { amount: 1000, lastCrimeAbs: 1 }, pirates: { amount: 1000, lastCrimeAbs: 1 } } } };
  for (const service of ["hire", "audience", "quest", "nobleQuest"]) {
    assert.ok(policy.wantedFacilityReason(wantedVisitor, { factionId: "north" }, service, 600));
    assert.equal(policy.wantedFacilityReason(wantedVisitor, { factionId: "citadel" }, service, 2), "");
    assert.equal(policy.wantedFacilityReason(wantedVisitor, { factionId: "north" }, service, 601), "");
  }
  assert.equal(policy.wantedFacilityReason(wantedVisitor, { factionId: "pirates", pirateHaven: true }, "quest", 2), "");
  for (const service of ["report", "compensation", "resign", "trade"]) assert.equal(policy.wantedFacilityReason(wantedVisitor, { factionId: "north" }, service, 2), "");
  wantedVisitor.wanted.byFaction.north.amount = 999;
  assert.equal(policy.wantedFacilityReason(wantedVisitor, { factionId: "north" }, "hire", 2), "");
  const suspended = { honorFactions: ["north"], wanted: { byFaction: { north: { amount: 1000, lastCrimeAbs: 1 } } } };
  assert.ok(policy.honorSuspensionReason(suspended, "north", 600));
  assert.equal(policy.honorSuspensionReason(suspended, "north", 601), "");
  assert.equal(policy.honorSuspensionReason(suspended, "citadel", 2), "");
  suspended.wanted.byFaction.north.amount = 999;
  assert.equal(policy.honorSuspensionReason(suspended, "north", 2), "");
  assert.equal(suspended.honorFactions[0], "north");
  const subject = { funds: 3000, honorFactions: ["north"], wanted: { byFaction: { north: { amount: 1000, lastCrimeAbs: 1 }, pirates: { amount: 500, lastCrimeAbs: 1 } }, history: [{ kind: "merchant_attack" }] } };
  for (const type of policy.CRIMINAL_ACTIONS) assert.ok(policy.crimeRestriction(subject, { type }));
  for (const type of ["merchant_rescue_help", "pirate_quest", "smuggle_attack"]) assert.equal(policy.crimeRestriction(subject, { type }), "");
  assert.equal(policy.crimeRestriction({ honorFactions: [] }, { type: "merchant_attack" }), "");
  assert.equal(policy.compensateWanted(subject, "north", 2, 999), false);
  assert.equal(subject.funds, 3000);
  assert.equal(policy.compensateWanted(subject, "north", 2, 1000), true);
  assert.equal(subject.funds, 1500);
  assert.equal(subject.wanted.byFaction.pirates.amount, 500);
  assert.equal(subject.wanted.history.length, 1);
  assert.equal(policy.compensateWanted(subject, "north", 2, 1000), false);
  assert.ok(policy.quoteWantedCompensation(subject, "pirates", 601).error);
  subject.funds = 749;
  assert.equal(policy.compensateWanted(subject, "pirates", 2, 500), false);
  const b = core.namespace, names = modules.get("name.js").namespace.REGIONAL_NAMES;
  for (const [fid, pool] of [["north", names.NORTH], ["archipelago", names.NORTH], ["citadel", names.WEST], ["pirates", Object.values(names).flat()]]) {
    const unique = [...new Set(pool)];
    for (let i = 0; i < unique.length; i++) assert.equal(b.rollBountyName(fid, () => (i + 0.5) / unique.length), unique[i]);
  }
  const data = b.normalizeBounties();
  const candidates = Array.from({ length: 400 }, (_, n) => ({ x: n % 20, y: Math.floor(n / 20) }));
  b.tickBounties(data, candidates, 120001, 4000, new Set(["0,0"]), null, () => 0);
  assert.equal(data.active.length, 10);
  assert.equal(new Set(data.active.map(s => s.templateId)).size, 10);
  assert.ok(data.active.every(s => s.position.x || s.position.y));
  assert.equal(new Set(data.active.map(s => `${s.position.x},${s.position.y}`)).size, 10);
  for (const s of data.active) {
    assert.ok(s.formation.length <= 20);
    assert.equal(s.total, s.formation.reduce((n, u) => n + u.count, 0));
    assert.equal(s.reward, Math.floor((s.total * 100 + 100) * 1.5));
  }
  const saved = JSON.stringify(data);
  b.tickBounties(data, candidates, 120030, 4000, new Set(), null, () => { throw Error("同季節の再抽選"); });
  assert.equal(JSON.stringify(data), saved);
  assert.equal(JSON.stringify(b.normalizeBounties(JSON.parse(saved))), saved);
  const id = data.active[0].id;
  assert.ok(b.claimBounty(data, id, 120030)); assert.equal(b.claimBounty(data, id, 120030), null);
  b.tickBounties(data, candidates, 120030, 4000); assert.equal(data.active.length, 9);
  b.tickBounties(data, candidates, 120031, 4001); assert.equal(data.active.length, 10);
  const keep = data.active.find(s => s.spawnedAbs === 120001);
  b.tickBounties(data, [], 120601, 4020, new Set(), keep.id);
  assert.ok(data.active.some(s => s.id === keep.id));
  b.tickBounties(data, [], 120601, 4020); assert.ok(!data.active.some(s => s.id === keep.id));
  const small = b.normalizeBounties(); b.tickBounties(small, [{ x: 1, y: 1 }], 1, 0); assert.equal(small.active.length, 1);
  const grid = [[{ terrain: "plain" }, { terrain: "mountain" }, { terrain: "sea" }], [{ terrain: "shoal" }, { terrain: "mountain" }, { terrain: "sea" }]];
  assert.equal(b.bountySeaPositions(grid, { x: 0, y: 0 }).length, 1);
  const wanted = await load("playerWanted.js"); await wanted.evaluate(); const w = wanted.namespace;
  const separate = {};
  w.recordCrime(separate, "merchant_attack", {}, 100, "north");
  w.recordCrime(separate, "checkpoint_force", {}, 200, "citadel");
  const unknown = {};
  assert.equal(w.recordCrime(separate, "merchant_attack", unknown, 300, "unknown"), 0);
  assert.equal(unknown.crimeRecorded, undefined);
  assert.equal(w.totalWanted(separate.wanted), 3000);
  assert.equal(w.expireWanted(separate.wanted, 699), false);
  assert.equal(w.expireWanted(separate.wanted, 700), true);
  assert.equal(separate.wanted.byFaction.north.amount, 0);
  assert.equal(separate.wanted.byFaction.citadel.amount, 2000);
  assert.equal(separate.wanted.history[0].factionId, "citadel");
  assert.equal(separate.wanted.history[0].amount, 2000);
  const migrated = w.normalizeWanted({amount:5000,lastCrimeAbs:100,history:[{kind:"merchant_attack",day:100}]});
  assert.equal(w.totalWanted(migrated), 0);
  assert.equal(migrated.history[0].factionId, null);
  assert.equal(migrated.history[0].amount, null);
  assert.equal(JSON.stringify(w.normalizeWanted(separate.wanted)), JSON.stringify(separate.wanted));
  const action = {}; assert.equal(w.recordCrime(state, "merchant_attack", action, 100, "north"), 1000);
  assert.equal(w.recordCrime(state, "merchant_attack", action, 101, "north"), 0);
  assert.equal(state.wanted.history.length, 1);
  assert.equal(state.wanted.history[0].kind, "merchant_attack");
  assert.equal(state.wanted.history[0].day, 100);
  assert.equal(w.recordCrime(state, "battle", {}, 101), 0);
  assert.equal(w.expireWanted(state.wanted, 699), false);
  assert.equal(w.recordCrime(state, "refugee_raid", {}, 699, "north"), 1500);
  assert.equal(w.totalWanted(state.wanted), 2500);
  assert.equal(w.expireWanted(state.wanted, 1298), false); assert.equal(w.expireWanted(state.wanted, 1299), true);
  assert.equal(w.totalWanted(state.wanted), 0);
  assert.equal(state.wanted.history.length, 2);
  assert.equal(state.wanted.history[0].kind, "refugee_raid");
  assert.equal(w.normalizeWanted({}).byFaction.north.lastCrimeAbs, null);
  assert.equal(w.normalizeWanted({amount: 1000, lastCrimeAbs: 100}).history.length, 0);
  const archive = {};
  for (let i = 0; i < 60; i++) w.recordCrime(archive, "pirate_quest", {}, 120001 + i, "north");
  assert.equal(archive.wanted.history.length, 50);
  assert.equal(archive.wanted.history.at(-1).day, 120011);
  assert.equal(archive.wanted.history[0].day, 120060);
  assert.equal(JSON.stringify(w.normalizeWanted(JSON.parse(JSON.stringify(archive.wanted)))), JSON.stringify(archive.wanted));
  assert.equal(w.normalizeWanted({history:[{kind:"unknown",day:1},{kind:"merchant_attack",day:NaN},null]}).history.length, 0);
  state.bounties = b.normalizeBounties(JSON.parse(saved));
  const world = await load("bountyWorld.js"); await world.evaluate();
  const shark = state.bounties.active.find(s => s.templateId === "shark");
  assert.ok(world.namespace.finishBounty(shark.id).length);
  assert.equal(state.funds, shark.reward); assert.equal(state.fleet.variants.length, 1);
  assert.equal(state.fleet.variants[0].variantId, "shark");
  assert.equal(state.fleet.variants[0].sourceName, b.bountyName(shark));
  for (const f of factions) for (const n of f.nobles) assert.equal(favors[n.id], f.id === shark.factionId ? -3 : 1);
  assert.equal(world.namespace.finishBounty(shark.id).length, 0); assert.equal(state.fleet.variants.length, 1); assert.equal(state.funds, shark.reward);
  // 公開UIの制限とイベント成立経路も、実際の関数を抽出して検証する。
  const uiSource = await fs.readFile(path.join(__dirname, "..", "bountyUI.js"), "utf8");
  const checks = vm.createContext({ state, totalTroops: () => 10 });
  Object.assign(checks, { CRIME_LABELS: modules.get("bountyConfig.js").namespace.CRIME_LABELS, CRIME_HISTORY_LIMIT: 50, DAY_PER_YEAR: 120, DAY_PER_SEASON: 30, SEASONS: ["春", "夏", "秋", "冬"], escapeHtml: s => s });
  vm.runInContext(uiSource.match(/function wantedCrimesHtml\([^\n]*\) \{[\s\S]*?\n\}/)[0], checks);
  checks.wanted = {history:[{kind:"merchant_attack",day:120001},{kind:"refugee_raid",day:120120}]};
  const crimeHtml = vm.runInContext("wantedCrimesHtml(wanted)", checks);
  assert.ok(crimeHtml.includes("神歴1000年 春 1日"));
  assert.ok(crimeHtml.includes("神歴1000年 冬 30日"));
  assert.ok(crimeHtml.includes("商人襲撃"));
  assert.ok(!/<details[^>]*\bopen\b/.test(crimeHtml));
  vm.runInContext(uiSource.match(/function bountyRestriction\([^\n]*\) \{[\s\S]*?\n\}/)[0], checks);
  checks.site = state.bounties.active.find(s => s.factionId === "north");
  state.honorFactions = ["north"];
  assert.ok(vm.runInContext("bountyRestriction(site)", checks));
  state.honorFactions = []; assert.equal(vm.runInContext("bountyRestriction(site)", checks), "");
  checks.totalTroops = () => 0; assert.ok(vm.runInContext("bountyRestriction(site)", checks));
  const source = await fs.readFile(path.join(__dirname, "..", "actions.js"), "utf8");
  const escapeContext = vm.createContext({ state: { wanted: {}, pendingEncounter: { pursuitKind: "regular" } }, finishPursuit: pursuitRules.finishPursuit, absDay: () => 20,
    clearBattlePrep() {}, setOutput() {}, pushLog() {}, pushToast() {}, syncUI() {} });
  const fullUI = await fs.readFile(path.join(__dirname, "..", "ui.js"), "utf8");
  vm.runInContext(fullUI.match(/function escapeBattleSuccess\([^\n]*\) \{[\s\S]*?\n\}/)[0], escapeContext);
  vm.runInContext('escapeBattleSuccess("祈りによる回避")', escapeContext);
  assert.equal(escapeContext.state.wanted.pursuitUntil, 23);
  const entryContext = vm.createContext({ state: { modeLabel: "normal", wanted: { byFaction: { north: { amount: 6000, lastCrimeAbs: 1 } } } },
    MODE_LABEL: { IN_TOWN: "town", IN_VILLAGE: "village" }, PLACE: { TOWN: "town", VILLAGE: "village" },
    getLocationStatus: () => ({ place: "town" }), getSettlementAtPosition: () => ({ factionId: "north" }),
    absDay: () => 2, wantedEntryReason: policy.wantedEntryReason, pushToast() {},
    isSettlementUnderSiege: () => { throw new Error("拒否後は入場処理へ進まない"); },
  });
  entryContext.state.position = { x: 0, y: 0 };
  vm.runInContext(source.match(/function attemptEnter\([^\n]*\) \{[\s\S]*?\n\}/)[0], entryContext);
  assert.equal(vm.runInContext('attemptEnter("town")', entryContext), false);
  assert.equal(entryContext.state.modeLabel, "normal");
  const eventState = { year: 1000, season: 0, day: 1, piracy: {checkpoint:{factionId:"north"}} };
  let blocked = false, starts = true;
  const eventContext = vm.createContext({ state: eventState, recordCrime: w.recordCrime, totalWanted: w.totalWanted, WANTED_FACTIONS: w.WANTED_FACTIONS, nearestSettlementInfo: () => ({factionId:"north"}), absDay: () => 120001,
    isBattleEventActionBlocked: () => blocked, pushLog() {}, pushToast() {},
    handlePirateCheckpoint: action => { if (starts) eventState.pendingEncounter = { active: true, enemyFactionId: "north" }; return action.type !== "unknown"; },
    handleChartPurchase: () => false, handleMerchantAction: () => false, handleFrontAction: () => false,
    handleSmuggleAction: () => false, handleRefugeeAction: () => false, handleCheckpointAction: () => false,
    handleOmenAction: () => false, handleWreckAction: () => false, handleTraitorAction: () => false,
  });
  vm.runInContext(source.match(/function handleTravelEventAction\([^\n]*\) \{[\s\S]*?\n\}/)[0], eventContext);
  for (const [type, amount] of [["merchant_attack", 1000], ["merchant_rescue_attack", 1000], ["refugee_attack", 1500], ["checkpoint_force", 2000], ["pirate_force", 2000]]) {
    eventState.pendingEncounter = null; eventState.wanted = w.normalizeWanted();
    eventContext.action = { type, payload:{factionId:"north"} };
    vm.runInContext("handleTravelEventAction(action)", eventContext);
    assert.equal(w.totalWanted(eventState.wanted), amount);
    vm.runInContext("handleTravelEventAction(action)", eventContext);
    assert.equal(w.totalWanted(eventState.wanted), amount);
  }
  eventState.pendingEncounter = null; eventState.wanted = w.normalizeWanted(); blocked = true;
  eventContext.action = { type: "merchant_attack" }; vm.runInContext("handleTravelEventAction(action)", eventContext);
  assert.equal(w.totalWanted(eventState.wanted), 0);
  blocked = false; starts = false; vm.runInContext("handleTravelEventAction(action)", eventContext);
  assert.equal(w.totalWanted(eventState.wanted), 0);
  starts = true; eventContext.action = { type: "merchant_rescue_help" }; vm.runInContext("handleTravelEventAction(action)", eventContext);
  assert.equal(w.totalWanted(eventState.wanted), 0);
  console.log("賞金首: 名前・固定編成・配置・補充・期限・二重報酬防止・関係変化・犯罪と手配解除: 全項目成功");
}
main().catch(error => { console.error(error); process.exitCode = 1; });
